// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package translator

import (
	agent "glossa/modules/agent"
	definition "glossa/modules/definition"
)

type TranslationConverterImpl struct{}

func (c *TranslationConverterImpl) ToSystemDefinition(source agent.LLMDefinition) definition.Definition {
	var definitionDefinition definition.Definition
	definitionDefinition.Definition = source.Definition
	definitionDefinition.Example = source.Example
	if source.Synonyms != nil {
		definitionDefinition.Synonyms = make([]string, len(source.Synonyms))
		for i := 0; i < len(source.Synonyms); i++ {
			definitionDefinition.Synonyms[i] = source.Synonyms[i]
		}
	}
	if source.Antonyms != nil {
		definitionDefinition.Antonyms = make([]string, len(source.Antonyms))
		for j := 0; j < len(source.Antonyms); j++ {
			definitionDefinition.Antonyms[j] = source.Antonyms[j]
		}
	}
	return definitionDefinition
}
func (c *TranslationConverterImpl) ToSystemDefinitionList(source []agent.LLMDefinition) []definition.Definition {
	var definitionDefinitionList []definition.Definition
	if source != nil {
		definitionDefinitionList = make([]definition.Definition, len(source))
		for i := 0; i < len(source); i++ {
			definitionDefinitionList[i] = c.ToSystemDefinition(source[i])
		}
	}
	return definitionDefinitionList
}
func (c *TranslationConverterImpl) ToSystemMeaning(source agent.LLMResponse) definition.Meaning {
	var definitionMeaning definition.Meaning
	definitionMeaning.PartOfSpeech = source.PartOfSpeech
	definitionMeaning.Translated = source.Translated
	definitionMeaning.Definitions = c.ToSystemDefinitionList(source.Definitions)
	return definitionMeaning
}
func (c *TranslationConverterImpl) ToSystemMeaningList(source []agent.LLMResponse) []definition.Meaning {
	var definitionMeaningList []definition.Meaning
	if source != nil {
		definitionMeaningList = make([]definition.Meaning, len(source))
		for i := 0; i < len(source); i++ {
			definitionMeaningList[i] = c.ToSystemMeaning(source[i])
		}
	}
	return definitionMeaningList
}
