// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package users

type UserConverterImpl struct{}

func (c *UserConverterImpl) ToDTO(source User) UserResponse {
	var usersUserResponse UserResponse
	usersUserResponse.ID = source.ID
	usersUserResponse.Email = source.Email
	usersUserResponse.DeletedAt = source.DeletedAt
	return usersUserResponse
}
func (c *UserConverterImpl) ToEntity(source CreateUserRequest) User {
	var usersUser User
	usersUser.Email = source.Email
	usersUser.Password = source.Password
	return usersUser
}
