// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package words

type WordConverterImpl struct{}

func (c *WordConverterImpl) ToDTO(source Word) WordResponse {
	var wordsWordResponse WordResponse
	wordsWordResponse.UserID = source.UserID
	wordsWordResponse.Origin = source.Origin
	wordsWordResponse.SourceLang = source.SourceLang
	wordsWordResponse.Translated = source.Translated
	wordsWordResponse.TargetLang = source.TargetLang
	wordsWordResponse.IsSaved = source.IsSaved
	return wordsWordResponse
}
func (c *WordConverterImpl) ToDTOList(source []Word) []WordResponse {
	var wordsWordResponseList []WordResponse
	if source != nil {
		wordsWordResponseList = make([]WordResponse, len(source))
		for i := 0; i < len(source); i++ {
			wordsWordResponseList[i] = c.ToDTO(source[i])
		}
	}
	return wordsWordResponseList
}
func (c *WordConverterImpl) ToEntity(source WordSavingRequest) Word {
	var wordsWord Word
	wordsWord.Origin = source.Origin
	wordsWord.SourceLang = source.SourceLang
	wordsWord.Translated = source.Translated
	wordsWord.TargetLang = source.TargetLang
	return wordsWord
}
